//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLanguage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KLanguage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbolSet k = { &quot;k&quot; }
        ///SymbolSet K = { &quot;K&quot; }
        ///
        ///GrammarElement &lt;C&gt; START = k
        ///GrammarElement &lt;C&gt; END = K
        ///GrammarElement &lt;M&gt; kORK = k or K
        ///GrammarElement &lt;C&gt; BYTE = kORK kORK kORK kORK kORK kORK kORK kORK [Delimiters=&quot; &quot;]
        ///GrammarElement &lt;C&gt; VARBYTE = &quot;KK&quot; BYTE
        ///GrammarElement &lt;M&gt; DATA = VARBYTE or BYTE 
        ///GrammarElement &lt;C&gt; PRINT = &quot;kK &quot; DATA* END
        ///GrammarElement &lt;C&gt; INPUT = &quot;KKKK &quot; BYTE END
        ///GrammarElement &lt;C&gt; DECLR = &quot;kkkk &quot; VARBYTE K
        ///GrammarElement &lt;M&gt; STMT = DECLR or PRINT or INPUT
        ///GrammarElement &lt;C&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KGrammar {
            get {
                return ResourceManager.GetString("KGrammar", resourceCulture);
            }
        }
    }
}
